//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWebToken.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Favorito")]
    public partial class Favorito
    {
        public int favoritoID { get; set; }
        public int perfilID { get; set; }
        public int cancionID { get; set; }
    
        public virtual Cancion Cancion { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
